//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadastroFornecedoresGrupoSym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CadastrosDbEntity : DbContext
    {
        public CadastrosDbEntity()
            : base("name=CadastrosDbEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssociacaoFornecedor> AssociacaoFornecedors { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Fornecedor> Fornecedors { get; set; }
    }
}
